<?php
require_once '../includes/config.php';
require_login();

$type = $_GET['type'] ?? '';
$file = $_GET['file'] ?? '';
$mode = $_GET['mode'] ?? 'open';

$allowedFolders = [
    'id' => 'id_applications',
    'cert' => 'certifications'
];

if (!isset($allowedFolders[$type]) || empty($file)) {
    http_response_code(400);
    echo 'Invalid request.';
    exit();
}

// Only allow simple filenames generated by the uploader
if (!preg_match('/^[A-Za-z0-9._-]+$/', $file)) {
    http_response_code(400);
    echo 'Invalid filename.';
    exit();
}

$baseDir = realpath(UPLOAD_DIR . $allowedFolders[$type]);
$filePath = realpath($baseDir . DIRECTORY_SEPARATOR . $file);

if ($baseDir === false || $filePath === false || strncmp($filePath, $baseDir, strlen($baseDir)) !== 0 || !file_exists($filePath)) {
    http_response_code(404);
    echo 'File not found.';
    exit();
}

$mimeType = mime_content_type($filePath) ?: 'application/octet-stream';
$disposition = ($mode === 'download') ? 'attachment' : 'inline';
$filename = basename($filePath);

header('Content-Type: ' . $mimeType);
header('Content-Length: ' . filesize($filePath));
header('Content-Disposition: ' . $disposition . '; filename="' . $filename . '"');
header('X-Content-Type-Options: nosniff');

// Clear output buffers to avoid corrupting binary output
while (ob_get_level()) {
    ob_end_clean();
}

$chunkSize = 8192;
$handle = fopen($filePath, 'rb');
if ($handle === false) {
    http_response_code(500);
    echo 'Unable to open file.';
    exit();
}

// Stream the file contents to the client
while (!feof($handle)) {
    echo fread($handle, $chunkSize);
    flush();
}

fclose($handle);
exit();
